name: Android Cloud Compiler

on:
  workflow_dispatch:
    inputs:
      project_url:
        description: 'URL do arquivo ZIP do projeto'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4
      
    - name: Baixar o Projeto do Celular
      run: curl -L "${{ github.event.inputs.project_url }}" -o project.zip
      
    - name: Extrair Arquivos
      run: unzip project.zip -d project_src
      
    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Dar permissão ao Gradle
      run: cd project_src && chmod +x gradlew
      
    - name: Compilar o APK
      run: cd project_src && ./gradlew assembleDebug
      
    - name: Salvar o APK gerado
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: project_src/app/build/outputs/apk/debug/*.apk
